name: msg-draft

services:

  interperso_01:

    container_name: cyrus_interperso_01

    build:
      context: ./Cyrus
      dockerfile: Dockerfile

    hostname: interperso01
    
    restart: unless-stopped

    cap_add:
      - SYS_PTRACE

    ports:
      - ${EXT_IMAP_PERS:-20143}:143
#      - ${EXT_IMAPS:-20993}:993
#      - ${EXT_HTTP:-28008}:8008

    networks:
      msg_draft_bridge:
        ipv4_address: 172.100.0.10

    volumes:
      - /etc/localtime:/etc/localtime:ro

  postfix_01:

    container_name: smtp_postfix_01

    build:
      context: ./Postfix
      dockerfile: Dockerfile

    hostname: smtp-postfix-01
    
    restart: unless-stopped

    cap_add:
      - SYS_PTRACE

    ports:
      - ${EXT_SMTP:-20025}:25

    networks:
      msg_draft_bridge:
        ipv4_address: 172.100.0.30

    volumes:
      - /etc/localtime:/etc/localtime:ro

  murder:

    container_name: cyrus_murder

    build:
      context: ./Cyrus
      dockerfile: Dockerfile

    hostname: mup
    
    restart: unless-stopped

    cap_add:
      - SYS_PTRACE

    networks:
      msg_draft_bridge:
        ipv4_address: 172.100.0.50

    volumes:
      - /etc/localtime:/etc/localtime:ro

  frontend_01:

    container_name: cyrus_frontend_01

    build:
      context: ./Cyrus
      dockerfile: Dockerfile

    hostname: frontend01
    
    restart: unless-stopped

    cap_add:
      - SYS_PTRACE

    ports:
      - ${EXT_IMAP_ORG:-21143}:143

    networks:
      msg_draft_bridge:
        ipv4_address: 172.100.0.61

    volumes:
      - /etc/localtime:/etc/localtime:ro

  frontend_02:

    container_name: cyrus_frontend_02

    build:
      context: ./Cyrus
      dockerfile: Dockerfile

    hostname: frontend02
    
    restart: unless-stopped

    cap_add:
      - SYS_PTRACE

    networks:
      msg_draft_bridge:
        ipv4_address: 172.100.0.62

    volumes:
      - /etc/localtime:/etc/localtime:ro

  backend_01:

    container_name: cyrus_backend_01

    build:
      context: ./Cyrus
      dockerfile: Dockerfile

    hostname: backend01
    
    restart: unless-stopped

    cap_add:
      - SYS_PTRACE

    networks:
      msg_draft_bridge:
        ipv4_address: 172.100.0.71

  backend_02:

    container_name: cyrus_backend_02

    build:
      context: ./Cyrus
      dockerfile: Dockerfile

    hostname: backend02
    
    restart: unless-stopped

    cap_add:
      - SYS_PTRACE

    networks:
      msg_draft_bridge:
        ipv4_address: 172.100.0.72

    volumes:
      - /etc/localtime:/etc/localtime:ro

  roundcube:
    container_name: roundcube_webmail
    image: roundcube/roundcubemail:1.6.11-apache  
    restart: unless-stopped
    hostname: roundcube
    ports:
      - ${EXT_WEBMAIL:-20080}:80
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=pgsql
      - ROUNDCUBEMAIL_DB_HOST=posgres
      - ROUNDCUBEMAIL_DB_PORT=5432
      - ROUNDCUBEMAIL_DB_USER=root
      - ROUNDCUBEMAIL_DB_PASSWORD=PasswordBdd
      - ROUNDCUBEMAIL_DB_NAME=roundcube
      - ROUNDCUBEMAIL_SKIN=elastic
      - ROUNDCUBEMAIL_DEFAULT_HOST=interperso_01
      - ROUNDCUBEMAIL_DEFAULT_PORT=143
      - ROUNDCUBEMAIL_SMTP_SERVER=cyrus
      - ROUNDCUBEMAIL_SMTP_PORT=25
      - ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE=10M
      - ROUNDCUBEMAIL_INSTALL_PLUGINS=1
    networks:
      msg_draft_bridge:
        ipv4_address: 172.100.0.5
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./Roundcube/config/config.inc.php:/var/www/html/config/config.inc.php
      - ./Roundcube/plugins/identity_switch:/var/www/html/plugins/identity_switch:ro
      - ./Roundcube/plugins/calendar:/var/www/html/plugins/calendar:ro
      - ./Roundcube/plugins/libcalendaring:/var/www/html/plugins/libcalendaring:ro
      - ./Roundcube/plugins/libkolab:/var/www/html/plugins/libkolab:ro
    depends_on:
      - db

  db:
    container_name: postgres_17.6
    image: postgres:17.6-alpine3.22
    restart: unless-stopped
    hostname: posgres
    # set shared memory limit pour l'utilisation Docker
    shm_size: 128mb
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: PasswordBdd
    networks:
      msg_draft_bridge:
        ipv4_address: 172.100.0.210
    volumes:
      - /etc/localtime:/etc/localtime:ro

  pgadmin:
    container_name: pgadmin4_9.8.0
    image: dpage/pgadmin4:9.8.0
    restart: unless-stopped
    hostname: pgadmin
    ports:
      - ${EXT_PGADMIN:-22080}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pg@admin.com
      PGADMIN_DEFAULT_PASSWORD: Password
    networks:
      msg_draft_bridge:
        ipv4_address: 172.100.0.200
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db

  agenda:
    container_name: baikal
    image: ckulka/baikal:0.10.1-nginx
    restart: unless-stopped
    hostname: agenda  
    ports:
      - ${EXT_AGENDA:-28080}:80
    networks:
      msg_draft_bridge:
        ipv4_address: 172.100.0.6
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./Baikal/baikal.yaml:/var/www/baikal/config/baikal.yaml
    depends_on:
      - db


networks:

  msg_draft_bridge:
    name: msg_draft_bridge
    driver: bridge
    ipam:
      config:
        - subnet: "172.100.0.0/24" 
          gateway: "172.100.0.1"
