---

- name: "Générer les fichiers pour Postfix"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    backup: no
  with_items:
    - { src: 'postfix/master.conf', dest: '/etc/postfix/master.cf', owner: 'root', group: 'root', mode: '0644' }
    - { src: 'postfix/main.conf', dest: '/etc/postfix/main.cf', owner: 'root', group: 'root', mode: '0644' }
  notify:
    restart_postfix
  tags:
    - install

- name: "Générer les fichiers pour Cyrus Imapd"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    backup: no
  with_items:
    - { src: 'cyrus/cyrus.conf', dest: '/etc/cyrus.conf', owner: 'root', group: 'root', mode: '0644' }
    - { src: 'cyrus/imapd.conf', dest: '/etc/imapd.conf', owner: 'root', group: 'root', mode: '0644' }
    - { src: 'cyrus/imapd-ext.conf', dest: '/etc/imapd-ext.conf', owner: 'root', group: 'root', mode: '0644' }
  notify:
    restart_cyrus
  tags:
    - install

- name: "Copier le fichier de transport"
  template:
    src: postfix/transport_to_mbx
    dest: /etc/postfix/transport_to_mbx
    owner: root
    group: root
    mode: '0644'
    backup: no
  register:
    rst_transport_to_mbx
  tags:
    - install 

- name: "Générer le fichier cdb"
  command: postmap cdb:/etc/postfix/transport_to_mbx
  when: rst_transport_to_mbx.changed
  notify:
    restart_cyrus
  tags:
    - install

- name: "Création de l'utilisateur de Cyrus"
  shell: echo -n "{{ item.password }}" | saslpasswd2 -p -c "{{ item.username }}"
  with_items:
    - { username: 'cyrus', password: 'Cyrus' }
  tags:
    - install

- name: "Activer Cyrus au démarrage"
  service:
    name: cyrus-imapd
    state: started
    enabled: yes
  tags:
    - install
