---

- name: "Ajout des utilisaturs de test pour l'authentification"
  shell: echo -n "{{ item.password }}" | saslpasswd2 -p -c "{{ item.username }}"
  with_items:
    - { username: 'benoit', password: 'Benoit' }
    - { username: 'cyril', password: 'Cyril' }
    - { username: 'julien', password: 'Julien' }
    - { username: 'jessy', password: 'Jessy' }
    - { username: 'olivier', password: 'Olivier' }
    - { username: 'samy', password: 'Samy' }
  when:
    inventory_hostname | upper is regex("^CYRUS_INTERPERSO_01$")
  tags:
    - sample

- name: "Création de mailbox interperso 01"
  shell: echo "cm user/{{ item.mailbox }}" | cyradm -u cyrus --password Cyrus localhost
  with_items:
    - { mailbox: 'benoit' }
    - { mailbox: 'cyril' }
    - { mailbox: 'julien' }
    - { mailbox: 'jessy' }
    - { mailbox: 'olivier' }
    - { mailbox: 'samy' }
  when:
    inventory_hostname | upper is regex("^CYRUS_INTERPERSO_01$")
  tags:
    - sample
